global:
  parameter_selection: ['x0_x','x0_y','x0_z','v0_x','v0_y','v0_z','g_x','g_y',"g_z",'w_x','w_y','w_z','b','m','a_x','a_y','a_z','r','A','Cd','rho']
  dtype: "float32"

data:
  converter: "flatten_tensor" # Converter to use for the data of the feature network
  load: True # Load or generate data
  load_path: "./data/bcnf-data/data1.pkl" # Path to the data if it should be loaded

  name: "data1"
  overwrite: True
  data_generation_config_file: "./configs/config.yaml"
  n_samples: 2000
  output_type: "trajectory"
  dt: 0.067
  T: 2.0
  ratio:
    - 16
    - 9
  fov_horizontal: 70.0
  cam1_pos: 0.0
  print_acc_rej: False
  num_cams: 2
  break_on_impact: False
  verbose: True

model:
  kwargs:
    size: 21
    nested_sizes: [16, 16, 16, 16, 16, 16, 16]
    n_conditions: 80
    n_blocks: 32
    dropout: 0.383
    act_norm: True

feature_network:
  type: null

time_series_network:
  type: LSTMFeatureNetwork
  kwargs:
    input_size: 3
    hidden_size: 16
    output_size: 80
    num_layers: 1
    dropout: 0.244
    bidirectional: True
    pooling: mean

optimizer:
  type: Adam
  kwargs:
    lr: 2e-4

lr_scheduler:
  type: ReduceLROnPlateau
  kwargs:
    mode: "min"
    factor: 0.5
    patience: 250
    threshold_mode: "abs"
    threshold: 1e-1

training:
  validation_split: 0.2
  val_loss_window_size: 10
  val_loss_patience: 500
  val_loss_tolerance: 1e-1
  val_loss_tolerance_mode: "abs"
  learning_rate: 2e-4
  n_folds: 3
  shuffle: False
  random_state: 2024_03_25
  batch_size: 256
  num_workers: 4
  pin_memory: True
  n_epochs: 50_000
  verbose: True
  timeout: 3600
  wandb:
    model_log_frequency: 10

